name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
            name: "with lua5.1",
            os: "ubuntu-latest",
            packages: "liblua5.1-dev libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev",
            cmake_opts: "-DSTANDALONE=1 -DWITH_LUAJIT=0 -DWITH_GTK3=FALSE"
          }
          - {
            name: "with luajit and gtk3",
            os: "ubuntu-latest",
            packages: "libluajit-5.1-dev libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev libgtk-3-dev",
            cmake_opts: "-DSTANDALONE=1 -DWITH_LUAJIT=1 -DWITH_GTK3=TRUE"
          }

    steps:
      - uses: actions/checkout@main

      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ${{ matrix.config.packages }}
          sudo apt-get install -y build-essential

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release ${{ matrix.config.cmake_opts }}

      - name: Build
        run: cmake --build ./build --config Release

#      - name: Create Artifact
#        run: |
#          cmake --install ./build

#      - name: Publish Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: standalone
#          path: build/standalone
