name: Windows version

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Windows version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc-mingw-w64-i686 mingw-w64-i686-dev binutils-mingw-w64-i686
          sudo apt-get install -y build-essential

      - name: Prep
        run: make windows-sdl2.tar.gz

      - name: Configure
        run: ./configure-mingw32.sh

      - name: Build
        run: make -f Makefile.mingw

      - name: Create Artifact
        run: make install -f Makefile.mingw

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: instead-win
          path: bin
          retention-days: 1
